-- casi_studio.id non aveva alcun generatore di default: le vecchie
-- versioni dell'app assegnavano l'id lato client (Date.now()), ma le
-- funzioni crea_caso_studio/ecc. lo omettono dall'INSERT assumendo che
-- il database lo generi da solo. Risultato: "null value in column id
-- violates not-null constraint" ad ogni nuova consegna passata dalla
-- funzione.
--
-- Rende id una colonna identity, partendo dal primo valore libero dopo
-- il più alto id già presente (così non collide con le righe esistenti,
-- inclusi i vecchi id-timestamp tipo 1700000000000).

alter table casi_studio alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('casi_studio', 'id'),
  greatest(coalesce((select max(id) from casi_studio), 0), 1)
);
